-- ============================================================
-- PROGEN 운영 DB 스키마 (참조용)
-- 2026-06-01 라이브 Supabase(public)에서 재생성 — 실제 운영 스키마와 일치.
-- 점진적 변경은 supabase/migrations/ 의 날짜별 .sql 이 단일 출처(source of truth).
-- 이 파일은 "현재 전체 모습"을 한눈에 보기 위한 스냅샷이다.
-- ※ crew_members.id 는 BIGINT(identity) — guests/events 등 UUID 테이블과 다름.
-- ============================================================

-- pgcrypto(gen_random_uuid) / uuid-ossp(uuid_generate_v4) — Supabase 기본 제공
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ── events (행사) ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  event_date TIMESTAMPTZ,
  is_mandatory BOOLEAN DEFAULT true,
  location TEXT,                                  -- 알림톡 #{장소}
  entry_time TEXT,                                -- 알림톡 #{입장시간}
  materials TEXT,                                 -- 알림톡 #{준비물}
  program_detail TEXT,                            -- 알림톡 #{진행내용}
  kakao_chat_url TEXT,                            -- 회차 채팅방 링크
  auto_checkin_alimtalk BOOLEAN NOT NULL DEFAULT false, -- /checkin 자동 출석문자(6/7번) 토글. 활성 행사 ON일 때만 발송
  cohort_id BIGINT REFERENCES cohorts(id),        -- 행사 소속 기수(2026-06-01). NULL=기수무관. 기존 행사는 1기 백필
  created_at TIMESTAMPTZ DEFAULT now()
);

-- ── crew_members (크루 지원자) ───────────────────────────────
-- ※ id 는 BIGINT identity (UUID 아님)
CREATE TABLE IF NOT EXISTS crew_members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT,
  phone TEXT UNIQUE,
  school TEXT,
  grade TEXT,
  age TEXT,
  major TEXT,
  path TEXT,
  project TEXT,
  gender TEXT,
  motivation TEXT,
  history TEXT,                                   -- 잔존 컬럼, 코드 미사용
  is_member BOOLEAN,                              -- true=포도(내부 전용)
  role TEXT DEFAULT 'participant',               -- 'participant' / 'staff'
  status TEXT DEFAULT '지원완료',
  noshow_count INTEGER DEFAULT 0,                 -- 누적 노쇼 (≥2 시 박탈)
  source_event_id UUID REFERENCES events(id),    -- 게스트→크루 전환 시 최초 유입 행사
  created_at TIMESTAMPTZ DEFAULT now()
);

-- ── guests (게스트) ──────────────────────────────────────────
-- ※ project / motivation 컬럼은 2026-04-02 운영 DB에서 직접 제거됨 (마이그레이션 파일 없음)
CREATE TABLE IF NOT EXISTS guests (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  name TEXT NOT NULL,
  phone TEXT NOT NULL UNIQUE,
  age TEXT,
  school TEXT,
  grade TEXT,
  major TEXT,
  path TEXT,
  gender TEXT,
  source_event_id UUID REFERENCES events(id),    -- 최초 유입 행사
  created_at TIMESTAMPTZ DEFAULT now()
);

-- ── event_registrations (행사 신청/출석) ─────────────────────
-- ※ crew_id 는 BIGINT (crew_members.id 가 BIGINT). 신청일 컬럼명은 registered_at.
CREATE TABLE IF NOT EXISTS event_registrations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  event_id UUID REFERENCES events(id) ON DELETE CASCADE,
  crew_id BIGINT REFERENCES crew_members(id) ON DELETE SET NULL,
  guest_id UUID REFERENCES guests(id) ON DELETE SET NULL,
  status TEXT DEFAULT '사전신청',                 -- '사전신청' / '출석완료' / '노쇼확정'
  team_name TEXT,
  checked_in_at TIMESTAMPTZ,
  deposit_status TEXT DEFAULT '미입금',           -- '미입금' / '입금' / '환불' (게스트 한정 의미)
  deposit_paid_at TIMESTAMPTZ,                    -- 마지막 상태 변경 시각
  refund_account TEXT,                            -- 게스트 환불 계좌 (예: "하나은행 110-123-456789")
  registered_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(crew_id, event_id)
);

-- ── feedbacks (피드백, 익명) ─────────────────────────────────
-- ※ crew_id / guest_id / score 컬럼 없음 (완전 익명 제출)
CREATE TABLE IF NOT EXISTS feedbacks (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  event_id UUID REFERENCES events(id) ON DELETE CASCADE,
  good_tags TEXT[] DEFAULT '{}',
  good_points TEXT DEFAULT '',
  bad_tags TEXT[] DEFAULT '{}',
  bad_points TEXT DEFAULT '',
  would_return BOOLEAN DEFAULT false,
  join_interest BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- ── reports (AI 보고서) ──────────────────────────────────────
CREATE TABLE IF NOT EXISTS reports (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  event_id UUID REFERENCES events(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  mode TEXT NOT NULL,                             -- 'general' / 'podo'
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- ── alimtalk_logs (알림톡 발송 로그) ─────────────────────────
CREATE TABLE IF NOT EXISTS alimtalk_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  template_code TEXT NOT NULL,                    -- 솔라피 카카오 템플릿 ID
  template_name TEXT,                             -- 사람이 읽는 이름
  to_phone TEXT NOT NULL,
  crew_id BIGINT REFERENCES crew_members(id) ON DELETE SET NULL,
  guest_id UUID REFERENCES guests(id) ON DELETE SET NULL,
  registration_id UUID REFERENCES event_registrations(id) ON DELETE SET NULL,
  event_id UUID REFERENCES events(id) ON DELETE SET NULL,
  status TEXT NOT NULL DEFAULT 'sent',           -- 'sent' / 'failed'
  solapi_message_id TEXT,
  error TEXT,
  variables JSONB,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- ── 인덱스 ───────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_event_registrations_deposit_status
  ON event_registrations(event_id, deposit_status) WHERE guest_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_alimtalk_logs_crew ON alimtalk_logs(crew_id);
CREATE INDEX IF NOT EXISTS idx_alimtalk_logs_guest ON alimtalk_logs(guest_id);
CREATE INDEX IF NOT EXISTS idx_alimtalk_logs_registration ON alimtalk_logs(registration_id);
CREATE INDEX IF NOT EXISTS idx_alimtalk_logs_event_template
  ON alimtalk_logs(event_id, template_code, status);

-- ── Row Level Security ───────────────────────────────────────
-- 7개 테이블 모두 RLS 활성화 + 정책 0개 = anon/public default-deny.
-- service_role 키(Next.js API)만 RLS 우회. 외부 anon 직접 접근 전면 차단.
ALTER TABLE events ENABLE ROW LEVEL SECURITY;
ALTER TABLE crew_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE guests ENABLE ROW LEVEL SECURITY;
ALTER TABLE event_registrations ENABLE ROW LEVEL SECURITY;
ALTER TABLE feedbacks ENABLE ROW LEVEL SECURITY;
ALTER TABLE reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE alimtalk_logs ENABLE ROW LEVEL SECURITY;
-- (정책 CREATE 없음 — 의도적 default-deny)

-- ============================================================
-- 기수(cohort) + 하반기 프로젝트(수료 관리) — 2026-06-01
-- 마이그레이션: supabase/migrations/2026-06-01_cohort_program.sql
-- ※ 신규 테이블 PK 전부 BIGINT identity. 크루 참조 FK 는 BIGINT.
-- ============================================================

-- ── cohorts (기수) ───────────────────────────────────────────
CREATE TABLE IF NOT EXISTS cohorts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  number INTEGER NOT NULL UNIQUE,                 -- 1, 2, 3...
  name TEXT NOT NULL,                             -- '1기'
  is_current BOOLEAN NOT NULL DEFAULT false,      -- 앱 전역 기본 선택 기수(항상 1개)
  started_on DATE,
  ended_on DATE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ── programs (기수당 누적 프로그램 + 수료 룰 설정의 단일 출처) ─
CREATE TABLE IF NOT EXISTS programs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cohort_id BIGINT NOT NULL REFERENCES cohorts(id) ON DELETE CASCADE,
  title TEXT NOT NULL,                            -- '1기 하반기 프로젝트'
  max_absences INTEGER NOT NULL DEFAULT 4,        -- 수료 컷: 결석 4회까지 허용(5회+→취소)
  weekly_cap INTEGER NOT NULL DEFAULT 1,          -- 주당 최대 인정 출석
  require_deliverables BOOLEAN NOT NULL DEFAULT true, -- 팀 결과물 AND 조건
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ── program_sessions (13주 + OT + 마감 + 수료식) ─────────────
CREATE TABLE IF NOT EXISTS program_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  program_id BIGINT NOT NULL REFERENCES programs(id) ON DELETE CASCADE,
  week_no INTEGER,                                -- 1..13 (OT/수료식은 NULL)
  label TEXT NOT NULL,                            -- 'OT','W1 클래스','W3 팀모임'...
  session_date DATE,
  deadline DATE,
  type TEXT NOT NULL DEFAULT 'team-meeting',      -- 'ot'|'class'|'pt'|'team-meeting'|'milestone'|'ceremony'
  counts_for_attendance BOOLEAN NOT NULL DEFAULT true, -- 출석 모수 대상
  event_id UUID REFERENCES events(id) ON DELETE SET NULL, -- 공식행사 연동(NULL=자율팀모임)
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ── program_teams (전 주차 고정 팀) ──────────────────────────
CREATE TABLE IF NOT EXISTS program_teams (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  program_id BIGINT NOT NULL REFERENCES programs(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(program_id, name)
);

-- ── program_enrollments (프로그램 ↔ 크루, 명단) ──────────────
CREATE TABLE IF NOT EXISTS program_enrollments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  program_id BIGINT NOT NULL REFERENCES programs(id) ON DELETE CASCADE,
  crew_id BIGINT NOT NULL REFERENCES crew_members(id) ON DELETE CASCADE, -- ★BIGINT
  team_id BIGINT REFERENCES program_teams(id) ON DELETE SET NULL,
  status TEXT NOT NULL DEFAULT '수강중',          -- '수강중'|'중도포기'|'수료'|'탈락'
  joined_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  decided_at TIMESTAMPTZ,
  note TEXT,
  UNIQUE(program_id, crew_id)
);

-- ── program_attendance (등록 ↔ 세션 = 매트릭스 셀) ───────────
CREATE TABLE IF NOT EXISTS program_attendance (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  enrollment_id BIGINT NOT NULL REFERENCES program_enrollments(id) ON DELETE CASCADE,
  session_id BIGINT NOT NULL REFERENCES program_sessions(id) ON DELETE CASCADE,
  present BOOLEAN NOT NULL DEFAULT false,
  source TEXT NOT NULL DEFAULT 'manual',          -- 'manual'|'checkin'
  evidence_url TEXT,
  evidence_note TEXT,
  recorded_by TEXT,
  recorded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(enrollment_id, session_id)               -- upsert 키
);

-- ── 결과물 (projects / specs / deliverables) ─────────────────
CREATE TABLE IF NOT EXISTS program_projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  program_id BIGINT NOT NULL REFERENCES programs(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  sort_order INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS program_deliverable_specs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT NOT NULL REFERENCES program_projects(id) ON DELETE CASCADE,
  name TEXT NOT NULL,                             -- '기획안','시안','영상','완성본'
  deadline DATE,
  sort_order INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS program_deliverables (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_id BIGINT NOT NULL REFERENCES program_teams(id) ON DELETE CASCADE,
  spec_id BIGINT NOT NULL REFERENCES program_deliverable_specs(id) ON DELETE CASCADE,
  submitted BOOLEAN NOT NULL DEFAULT false,
  submitted_at TIMESTAMPTZ,
  link TEXT,
  recorded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(team_id, spec_id)                        -- 그리드 셀
);

-- ── 인덱스 (cohort/program) ──────────────────────────────────
CREATE UNIQUE INDEX IF NOT EXISTS uq_cohorts_single_current
  ON cohorts(is_current) WHERE is_current = true;
CREATE INDEX IF NOT EXISTS idx_events_cohort ON events(cohort_id);
CREATE INDEX IF NOT EXISTS idx_programs_cohort ON programs(cohort_id);
CREATE INDEX IF NOT EXISTS idx_program_sessions_program ON program_sessions(program_id, sort_order);
CREATE UNIQUE INDEX IF NOT EXISTS uq_program_sessions_event
  ON program_sessions(event_id) WHERE event_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_program_enrollments_program ON program_enrollments(program_id);
CREATE INDEX IF NOT EXISTS idx_program_attendance_session ON program_attendance(session_id);
CREATE INDEX IF NOT EXISTS idx_program_projects_program ON program_projects(program_id, sort_order);
CREATE INDEX IF NOT EXISTS idx_program_deliverable_specs_project ON program_deliverable_specs(project_id, sort_order);
CREATE INDEX IF NOT EXISTS idx_program_deliverables_team ON program_deliverables(team_id);

-- ── RLS (cohort/program 9개 테이블 — 동일 default-deny) ───────
ALTER TABLE cohorts ENABLE ROW LEVEL SECURITY;
ALTER TABLE programs ENABLE ROW LEVEL SECURITY;
ALTER TABLE program_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE program_teams ENABLE ROW LEVEL SECURITY;
ALTER TABLE program_enrollments ENABLE ROW LEVEL SECURITY;
ALTER TABLE program_attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE program_projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE program_deliverable_specs ENABLE ROW LEVEL SECURITY;
ALTER TABLE program_deliverables ENABLE ROW LEVEL SECURITY;
