-- ============================================================
-- 기수(cohort) + 하반기 프로젝트(수료 관리) 서브시스템 (2026-06-01)
-- ------------------------------------------------------------
-- 기존 시스템(행사 독립 운영)을 깨지 않고 더하는 additive 변경.
--  · cohorts(기수) = 데이터 차원. events.cohort_id 로 기존 행사에 기수 부착(1기 백필).
--  · programs(누적 프로그램) ─ sessions(13주+OT) ─ enrollments(명단)
--    ─ teams ─ attendance(매트릭스 셀) ─ projects/specs/deliverables(결과물).
--  · 수료 = 개인 출석(결석 4회까지) AND 팀 결과물 기한내 제출. 판정은 계산값(저장X).
--  ※ crew_members.id 는 BIGINT → 크루 참조 FK 전부 BIGINT (UUID 금지).
--  ※ 신규 테이블 PK 는 전부 BIGINT identity.
-- ============================================================

-- ── 1.1 cohorts (기수) ───────────────────────────────────────
CREATE TABLE IF NOT EXISTS cohorts (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  number      INTEGER NOT NULL UNIQUE,          -- 1, 2, 3 ...
  name        TEXT NOT NULL,                    -- '1기'
  is_current  BOOLEAN NOT NULL DEFAULT false,   -- 앱 전역 기본 선택 기수
  started_on  DATE,
  ended_on    DATE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
-- 현재 기수는 항상 1개만
CREATE UNIQUE INDEX IF NOT EXISTS uq_cohorts_single_current
  ON cohorts(is_current) WHERE is_current = true;

-- 1기 시드 (멱등: number UNIQUE 충돌 무시)
INSERT INTO cohorts (number, name, is_current)
VALUES (1, '1기', true)
ON CONFLICT (number) DO NOTHING;

-- ── 1.2 events.cohort_id (기존 행사에 기수 부착) ──────────────
-- 크루는 전역 유지(컬럼 안 붙임). "이 기수 참여" 사실은 program_enrollments 가 링크.
ALTER TABLE events ADD COLUMN IF NOT EXISTS cohort_id BIGINT REFERENCES cohorts(id);
CREATE INDEX IF NOT EXISTS idx_events_cohort ON events(cohort_id);
COMMENT ON COLUMN events.cohort_id IS '행사 소속 기수. NULL=기수무관. 기존 행사는 1기 백필.';

-- 기존 행사 전부 1기로 백필
UPDATE events
SET cohort_id = (SELECT id FROM cohorts WHERE number = 1)
WHERE cohort_id IS NULL;

-- ── 1.3 programs (기수당 누적 프로그램 + 룰 설정의 단일 출처) ──
CREATE TABLE IF NOT EXISTS programs (
  id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cohort_id            BIGINT NOT NULL REFERENCES cohorts(id) ON DELETE CASCADE,
  title                TEXT NOT NULL,                       -- '1기 하반기 프로젝트'
  max_absences         INTEGER NOT NULL DEFAULT 4,          -- 수료 컷: 결석 4회까지 허용(5회+→취소)
  weekly_cap           INTEGER NOT NULL DEFAULT 1,          -- 주당 최대 인정 출석
  require_deliverables BOOLEAN NOT NULL DEFAULT true,       -- 팀 결과물 AND 조건
  created_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_programs_cohort ON programs(cohort_id);

-- 1기 하반기 프로젝트 시드 (멱등: 이미 있으면 스킵)
INSERT INTO programs (cohort_id, title)
SELECT c.id, '1기 하반기 프로젝트'
FROM cohorts c
WHERE c.number = 1
  AND NOT EXISTS (
    SELECT 1 FROM programs p WHERE p.cohort_id = c.id
  );

-- ── 1.4 program_sessions (13주 + OT + 마감 + 수료식) ──────────
CREATE TABLE IF NOT EXISTS program_sessions (
  id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  program_id            BIGINT NOT NULL REFERENCES programs(id) ON DELETE CASCADE,
  week_no               INTEGER,                            -- 1..13 (OT/수료식은 NULL)
  label                 TEXT NOT NULL,                      -- 'OT','W1 클래스','W3 팀모임'...
  session_date          DATE,
  deadline              DATE,
  type                  TEXT NOT NULL DEFAULT 'team-meeting', -- 'ot'|'class'|'pt'|'team-meeting'|'milestone'|'ceremony'
  counts_for_attendance BOOLEAN NOT NULL DEFAULT true,      -- 출석 모수 대상
  event_id              UUID REFERENCES events(id) ON DELETE SET NULL, -- 공식행사 연동(NULL=자율팀모임)
  sort_order            INTEGER NOT NULL DEFAULT 0,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_program_sessions_program ON program_sessions(program_id, sort_order);
-- 1행사 ↔ 1세션 (체크인 브릿지 결정성)
CREATE UNIQUE INDEX IF NOT EXISTS uq_program_sessions_event
  ON program_sessions(event_id) WHERE event_id IS NOT NULL;

-- ── 1.5 program_teams (전 주차 고정 팀) ──────────────────────
CREATE TABLE IF NOT EXISTS program_teams (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  program_id BIGINT NOT NULL REFERENCES programs(id) ON DELETE CASCADE,
  name       TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(program_id, name)
);

-- ── 1.6 program_enrollments (프로그램 ↔ 크루, 명단) ───────────
CREATE TABLE IF NOT EXISTS program_enrollments (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  program_id BIGINT NOT NULL REFERENCES programs(id) ON DELETE CASCADE,
  crew_id    BIGINT NOT NULL REFERENCES crew_members(id) ON DELETE CASCADE,  -- ★BIGINT
  team_id    BIGINT REFERENCES program_teams(id) ON DELETE SET NULL,
  status     TEXT NOT NULL DEFAULT '수강중',   -- '수강중'|'중도포기'|'수료'|'탈락'
  joined_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  decided_at TIMESTAMPTZ,
  note       TEXT,
  UNIQUE(program_id, crew_id)
);
CREATE INDEX IF NOT EXISTS idx_program_enrollments_program ON program_enrollments(program_id);

-- ── 1.7 program_attendance (등록 ↔ 세션 = 매트릭스 셀) ────────
CREATE TABLE IF NOT EXISTS program_attendance (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  enrollment_id BIGINT NOT NULL REFERENCES program_enrollments(id) ON DELETE CASCADE,
  session_id    BIGINT NOT NULL REFERENCES program_sessions(id) ON DELETE CASCADE,
  present       BOOLEAN NOT NULL DEFAULT false,
  source        TEXT NOT NULL DEFAULT 'manual',   -- 'manual'|'checkin'
  evidence_url  TEXT,
  evidence_note TEXT,
  recorded_by   TEXT,
  recorded_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(enrollment_id, session_id)               -- upsert 키
);
CREATE INDEX IF NOT EXISTS idx_program_attendance_session ON program_attendance(session_id);

-- ── 1.8 결과물 (projects / specs / deliverables) ──────────────
CREATE TABLE IF NOT EXISTS program_projects (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  program_id BIGINT NOT NULL REFERENCES programs(id) ON DELETE CASCADE,
  name       TEXT NOT NULL,                        -- 'AI 캐릭터 굿즈' 등
  sort_order INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_program_projects_program ON program_projects(program_id, sort_order);

CREATE TABLE IF NOT EXISTS program_deliverable_specs (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT NOT NULL REFERENCES program_projects(id) ON DELETE CASCADE,
  name       TEXT NOT NULL,                        -- '기획안','시안','영상','완성본'
  deadline   DATE,
  sort_order INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_program_deliverable_specs_project ON program_deliverable_specs(project_id, sort_order);

CREATE TABLE IF NOT EXISTS program_deliverables (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_id      BIGINT NOT NULL REFERENCES program_teams(id) ON DELETE CASCADE,
  spec_id      BIGINT NOT NULL REFERENCES program_deliverable_specs(id) ON DELETE CASCADE,
  submitted    BOOLEAN NOT NULL DEFAULT false,
  submitted_at TIMESTAMPTZ,
  link         TEXT,
  recorded_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(team_id, spec_id)                         -- 그리드 셀
);
CREATE INDEX IF NOT EXISTS idx_program_deliverables_team ON program_deliverables(team_id);

-- ── 1.9 RLS ──────────────────────────────────────────────────
-- 기존 7개 테이블과 동일: RLS 활성화 + 정책 0개 = anon/public default-deny.
-- service_role(우리 Next.js API)만 접근.
ALTER TABLE cohorts                   ENABLE ROW LEVEL SECURITY;
ALTER TABLE programs                  ENABLE ROW LEVEL SECURITY;
ALTER TABLE program_sessions          ENABLE ROW LEVEL SECURITY;
ALTER TABLE program_teams             ENABLE ROW LEVEL SECURITY;
ALTER TABLE program_enrollments       ENABLE ROW LEVEL SECURITY;
ALTER TABLE program_attendance        ENABLE ROW LEVEL SECURITY;
ALTER TABLE program_projects          ENABLE ROW LEVEL SECURITY;
ALTER TABLE program_deliverable_specs ENABLE ROW LEVEL SECURITY;
ALTER TABLE program_deliverables      ENABLE ROW LEVEL SECURITY;
-- (정책 CREATE 없음 — 의도적 default-deny)
